language: node_js
node_js:
  - "12.9.1"
script:
  - echo "Deploying!"
  - npm install
  - npm build
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
