language: node_js
node_js:
  - "12.16.3"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install
  - npm run build

script:
  - firebase deploy --token $FIREBASE_TOKEN
